workflows:
  android-full-featured:
    name: APK Pro - Carte + GPS + Photos
    environment:
      flutter: 3.41.1
    scripts:
      - flutter clean
      - flutter pub get
      - '[ -f assets/icon.png ] && flutter pub run flutter_launcher_icons:main || echo "no icon"'
      - flutter create --platforms android .
      - mkdir -p android/app/src/main/res/xml

      # Créer network_security_config.xml
      - |
        cat <<EOF > android/app/src/main/res/xml/network_security_config.xml
        <?xml version="1.0" encoding="utf-8"?>
        <network-security-config>
            <base-config cleartextTrafficPermitted="false">
                <trust-anchors>
                    <certificates src="system"/>
                </trust-anchors>
            </base-config>
            <domain-config cleartextTrafficPermitted="true">
                <domain includeSubdomains="true">tile.openstreetmap.org</domain>
                <domain includeSubdomains="true">tile.openstreetmap.fr</domain>
            </domain-config>
        </network-security-config>
        EOF

      # Supprimer les anciennes permissions pour éviter le conflit
      - sed -i '' '/<uses-permission android:name=/d' android/app/src/main/AndroidManifest.xml

      # Ajouter toutes les permissions nécessaires en UNE seule ligne
      - sed -i '' 's|<application |<uses-permission android:name="android.permission.INTERNET"/><uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/><uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/><uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/><uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/><uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/><uses-permission android:name="android.permission.CAMERA"/><application |' android/app/src/main/AndroidManifest.xml

      # Ajouter networkSecurityConfig dans <application>
      - sed -i '' 's|<application |<application android:networkSecurityConfig="@xml/network_security_config" |' android/app/src/main/AndroidManifest.xml

      # Build APK
      - flutter build apk --debug
      - flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
      - build/app/outputs/flutter-apk/app-release.apk