workflows:
  android-apk:
    name: Android APK Debug
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: 3.41.1
      vars:
        CLOUD_FIRESTORE_VERSION: 6.1.2
        FIREBASE_CORE_VERSION: 4.4.0
        FIREBASE_STORAGE_VERSION: 13.0.6
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK Debug
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
      - build/app/outputs/**/*.apk
