workflows:
  android-build:
    name: Android Build
    max_build_duration: 30
    environment:
      flutter: 3.19.6   # ⚠️ Mets ici TA version flutter exacte
      xcode: latest
      vars:
        PACKAGE_NAME: "com.example.nid_poule_app"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter pub get

      - name: Build Android AppBundle
        script: |
          flutter build appbundle --debug

    artifacts:
      - build/app/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - mohammed.mezouar@gmail.com
