workflows:
  apk-debug:
    name: APK Debug
    environment:
      flutter: 3.41.1
    scripts:
      - flutter pub get
      - flutter build apk --debug
    artifacts:
      - build/app/outputs/**/*.apk
