workflows:
  android-release:
    name: Nid Poule APK
    environment:
      flutter: 3.41.1

    scripts:
      - flutter clean
      - flutter pub get

      # Générer Android si absent
      - flutter create --platforms android .

      # Créer dossier xml si absent
      - mkdir -p android/app/src/main/res/xml

      # Créer network_security_config.xml
      - |
        cat <<EOF > android/app/src/main/res/xml/network_security_config.xml
        <?xml version="1.0" encoding="utf-8"?>
        <network-security-config>
            <base-config cleartextTrafficPermitted="true" />
        </network-security-config>
        EOF

      # Ajouter networkSecurityConfig dans <application>
      - sed -i 's|<application |<application android:networkSecurityConfig="@xml/network_security_config" |' android/app/src/main/AndroidManifest.xml

      # Build release
      - flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk