workflows:
  android-apk-clean-create:
    name: APK Clean Build with Android Create
    environment:
      flutter: 3.41.1

    scripts:
      # --- 1️⃣ Nettoyage avant tout ---
      - name: Clean Flutter
        script: |
          echo "=== Nettoyage Flutter ==="
          flutter clean

      # --- 2️⃣ Créer le dossier Android proprement ---
      - name: Create Android folder
        script: |
          echo "=== Création du dossier Android ==="
          flutter create --platforms android .

      # --- 3️⃣ Récupérer les packages Dart/Flutter ---
      - name: Get packages
        script: flutter pub get

      # --- 4️⃣ Build APK debug ---
      - name: Build APK Debug
        script: flutter build apk --debug --no-shrink

    artifacts:
      - build/app/outputs/**/*.apk