workflows:
  android-apk:
    name: APK Clean Build
    environment:
      flutter: 3.41.1

    scripts:
      - name: Get packages
        script: flutter pub get

      - name: Build APK Debug
        script: flutter build apk --debug

    artifacts:
      - build/app/outputs/**/*.apk
