workflows:
  android-apk-clean-create:
    name: APK Clean Build + Android Create
    environment:
      flutter: 3.41.1

    scripts:
      # --- 1️⃣ Nettoyage Flutter ---
      - name: Clean Flutter
        script: |
          echo "=== Nettoyage Flutter ==="
          flutter clean
          rm -rf android/.gradle
          rm -rf android/app/build

      # --- 2️⃣ Récupérer les packages Dart/Flutter AVANT la création Android ---
      - name: Get packages
        script: flutter pub get

      # --- 3️⃣ Créer le dossier Android proprement ---
      - name: Create Android folder
        script: |
          echo "=== Création du dossier Android ==="
          flutter create --platforms android .

      # --- 4️⃣ Build APK debug ---
      - name: Build APK Debug
        script: flutter build apk --debug --no-shrink

    artifacts:
      - build/app/outputs/**/*.apk