workflows:
  android-full-featured:
    name: APK Pro - Carte + GPS + Photos

    environment:
      flutter: 3.41.1

    scripts:
      - name: Clean everything
        script: |
          rm -rf android ios web
          flutter clean

      - name: Get packages
        script: flutter pub get

      - name: Create platforms
        script: flutter create --platforms android .

      - name: Setup Android permissions & network
        script: |
          mkdir -p android/app/src/main/res/xml

          cat << 'EOF' > android/app/src/main/res/xml/network_security_config.xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="false">
        <trust-anchors>
            <certificates src="system"/>
        </trust-anchors>
    </base-config>
    <domain-config>
        <domain includeSubdomains="true">tile.openstreetmap.org</domain>
        <domain includeSubdomains="true">tile.openstreetmap.fr</domain>
        <domain includeSubdomains="true">a.tile.openstreetmap.org</domain>
        <domain includeSubdomains="true">b.tile.openstreetmap.org</domain>
        <domain includeSubdomains="true">c.tile.openstreetmap.org</domain>
    </domain-config>
</network-security-config>
EOF

          cat << 'EOF' > android/app/src/main/AndroidManifest.xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
    <uses-permission android:name="android.permission.CAMERA"/>

    <application
        android:label="NidPoule"
        android:name="android.app.Application"
        android:icon="@mipmap/ic_launcher"
        android:networkSecurityConfig="@xml/network_security_config">

        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">

            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/NormalTheme"/>

            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

        </activity>

        <meta-data
            android:name="flutterEmbedding"
            android:value="2"/>

    </application>
</manifest>
EOF

      - name: Gradle clean
        script: |
          cd android
          ./gradlew clean --stop
          cd ..

      - name: Build APK
        script: flutter build apk --debug

    artifacts:
      - build/app/outputs/**/*.apk